services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: DB_USER
        value: 2xrafZsJdgAnJfX.root
      - key: DB_PASS
        value: JJwvo3wRtW2bIzjc
      - key: DB_HOST
        value: gateway01.us-west-2.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: 4000
      - key: DB_NAME
        value: inventory
      - key: DB_CA
        value: ./ca.pem
      - key: RENDER
        value: true
      - key: SECRET_KEY
        value: KJBCIJBWJU6674r2ghjhj*7nkhhloi
      - key: FRONTEND_URL
        value: https://inventory-one-wheat.vercel.app/
